//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace AsmodatForexEngineAPI.com.efxnow.demoweb.authentyficationservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationServiceSoap", Namespace="www.GainCapital.com.WebServices")]
    public partial class AuthenticationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Authenticator authenticatorValueField;
        
        private System.Threading.SendOrPostCallback AuthenticateCredentialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateCredentialsWithBrandCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateLinkedAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServerTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SingleSignOnOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateWithDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthenticationService() {
            this.Url = global::AsmodatForexEngineAPI.Properties.Settings.Default.AsmodatForexEngineAPI_com_efxnow_demoweb_AuthenticationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authenticator AuthenticatorValue {
            get {
                return this.authenticatorValueField;
            }
            set {
                this.authenticatorValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticateCredentialsCompletedEventHandler AuthenticateCredentialsCompleted;
        
        /// <remarks/>
        public event AuthenticateCredentialsWithBrandCodeCompletedEventHandler AuthenticateCredentialsWithBrandCodeCompleted;
        
        /// <remarks/>
        public event AuthenticateLinkedAccountCompletedEventHandler AuthenticateLinkedAccountCompleted;
        
        /// <remarks/>
        public event GetServerTimeCompletedEventHandler GetServerTimeCompleted;
        
        /// <remarks/>
        public event SingleSignOnCompletedEventHandler SingleSignOnCompleted;
        
        /// <remarks/>
        public event AuthenticateWithDetailsCompletedEventHandler AuthenticateWithDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticatorValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.GainCapital.com.WebServices/AuthenticateCredentials", RequestNamespace="www.GainCapital.com.WebServices", ResponseNamespace="www.GainCapital.com.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticationResult", IsNullable=true)]
        public AuthenticationResult AuthenticateCredentials(string userID, string password) {
            object[] results = this.Invoke("AuthenticateCredentials", new object[] {
                        userID,
                        password});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateCredentialsAsync(string userID, string password) {
            this.AuthenticateCredentialsAsync(userID, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateCredentialsAsync(string userID, string password, object userState) {
            if ((this.AuthenticateCredentialsOperationCompleted == null)) {
                this.AuthenticateCredentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateCredentialsOperationCompleted);
            }
            this.InvokeAsync("AuthenticateCredentials", new object[] {
                        userID,
                        password}, this.AuthenticateCredentialsOperationCompleted, userState);
        }
        
        private void OnAuthenticateCredentialsOperationCompleted(object arg) {
            if ((this.AuthenticateCredentialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCredentialsCompleted(this, new AuthenticateCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticatorValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.GainCapital.com.WebServices/AuthenticateCredentialsWithBrandCode", RequestNamespace="www.GainCapital.com.WebServices", ResponseNamespace="www.GainCapital.com.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticationResult", IsNullable=true)]
        public AuthenticationResult AuthenticateCredentialsWithBrandCode(string userID, string password, string brandCode) {
            object[] results = this.Invoke("AuthenticateCredentialsWithBrandCode", new object[] {
                        userID,
                        password,
                        brandCode});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateCredentialsWithBrandCodeAsync(string userID, string password, string brandCode) {
            this.AuthenticateCredentialsWithBrandCodeAsync(userID, password, brandCode, null);
        }
        
        /// <remarks/>
        public void AuthenticateCredentialsWithBrandCodeAsync(string userID, string password, string brandCode, object userState) {
            if ((this.AuthenticateCredentialsWithBrandCodeOperationCompleted == null)) {
                this.AuthenticateCredentialsWithBrandCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateCredentialsWithBrandCodeOperationCompleted);
            }
            this.InvokeAsync("AuthenticateCredentialsWithBrandCode", new object[] {
                        userID,
                        password,
                        brandCode}, this.AuthenticateCredentialsWithBrandCodeOperationCompleted, userState);
        }
        
        private void OnAuthenticateCredentialsWithBrandCodeOperationCompleted(object arg) {
            if ((this.AuthenticateCredentialsWithBrandCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCredentialsWithBrandCodeCompleted(this, new AuthenticateCredentialsWithBrandCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticatorValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.GainCapital.com.WebServices/AuthenticateLinkedAccount", RequestNamespace="www.GainCapital.com.WebServices", ResponseNamespace="www.GainCapital.com.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticationResult", IsNullable=true)]
        public AuthenticationResult AuthenticateLinkedAccount(string token, string AccountNumber) {
            object[] results = this.Invoke("AuthenticateLinkedAccount", new object[] {
                        token,
                        AccountNumber});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateLinkedAccountAsync(string token, string AccountNumber) {
            this.AuthenticateLinkedAccountAsync(token, AccountNumber, null);
        }
        
        /// <remarks/>
        public void AuthenticateLinkedAccountAsync(string token, string AccountNumber, object userState) {
            if ((this.AuthenticateLinkedAccountOperationCompleted == null)) {
                this.AuthenticateLinkedAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateLinkedAccountOperationCompleted);
            }
            this.InvokeAsync("AuthenticateLinkedAccount", new object[] {
                        token,
                        AccountNumber}, this.AuthenticateLinkedAccountOperationCompleted, userState);
        }
        
        private void OnAuthenticateLinkedAccountOperationCompleted(object arg) {
            if ((this.AuthenticateLinkedAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateLinkedAccountCompleted(this, new AuthenticateLinkedAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticatorValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.GainCapital.com.WebServices/GetServerTime", RequestNamespace="www.GainCapital.com.WebServices", ResponseNamespace="www.GainCapital.com.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetServerTime() {
            object[] results = this.Invoke("GetServerTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerTimeAsync() {
            this.GetServerTimeAsync(null);
        }
        
        /// <remarks/>
        public void GetServerTimeAsync(object userState) {
            if ((this.GetServerTimeOperationCompleted == null)) {
                this.GetServerTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerTimeOperationCompleted);
            }
            this.InvokeAsync("GetServerTime", new object[0], this.GetServerTimeOperationCompleted, userState);
        }
        
        private void OnGetServerTimeOperationCompleted(object arg) {
            if ((this.GetServerTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerTimeCompleted(this, new GetServerTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticatorValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.GainCapital.com.WebServices/SingleSignOn", RequestNamespace="www.GainCapital.com.WebServices", ResponseNamespace="www.GainCapital.com.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticationResponse", IsNullable=true)]
        public AuthenticationResponse SingleSignOn([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AuthenticationRequest AuthenticationRequest) {
            object[] results = this.Invoke("SingleSignOn", new object[] {
                        AuthenticationRequest});
            return ((AuthenticationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SingleSignOnAsync(AuthenticationRequest AuthenticationRequest) {
            this.SingleSignOnAsync(AuthenticationRequest, null);
        }
        
        /// <remarks/>
        public void SingleSignOnAsync(AuthenticationRequest AuthenticationRequest, object userState) {
            if ((this.SingleSignOnOperationCompleted == null)) {
                this.SingleSignOnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSingleSignOnOperationCompleted);
            }
            this.InvokeAsync("SingleSignOn", new object[] {
                        AuthenticationRequest}, this.SingleSignOnOperationCompleted, userState);
        }
        
        private void OnSingleSignOnOperationCompleted(object arg) {
            if ((this.SingleSignOnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SingleSignOnCompleted(this, new SingleSignOnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticatorValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.GainCapital.com.WebServices/AuthenticateWithDetails", RequestNamespace="www.GainCapital.com.WebServices", ResponseNamespace="www.GainCapital.com.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthenticationResult2 AuthenticateWithDetails(string userID, string password) {
            object[] results = this.Invoke("AuthenticateWithDetails", new object[] {
                        userID,
                        password});
            return ((AuthenticationResult2)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateWithDetailsAsync(string userID, string password) {
            this.AuthenticateWithDetailsAsync(userID, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateWithDetailsAsync(string userID, string password, object userState) {
            if ((this.AuthenticateWithDetailsOperationCompleted == null)) {
                this.AuthenticateWithDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateWithDetailsOperationCompleted);
            }
            this.InvokeAsync("AuthenticateWithDetails", new object[] {
                        userID,
                        password}, this.AuthenticateWithDetailsOperationCompleted, userState);
        }
        
        private void OnAuthenticateWithDetailsOperationCompleted(object arg) {
            if ((this.AuthenticateWithDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateWithDetailsCompleted(this, new AuthenticateWithDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="www.GainCapital.com.WebServices", IsNullable=false)]
    public partial class Authenticator : System.Web.Services.Protocols.SoapHeader {
        
        private string applicationNameField;
        
        private string iPAddressField;
        
        private string machineNameField;
        
        private string languageField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string MachineName {
            get {
                return this.machineNameField;
            }
            set {
                this.machineNameField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class SystemDetails {
        
        private string serverNameField;
        
        private string accountNumberField;
        
        private string metaAccountNumberField;
        
        /// <remarks/>
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MetaAccountNumber {
            get {
                return this.metaAccountNumberField;
            }
            set {
                this.metaAccountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class ServiceEndPoint {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class AuthenticationResponse {
        
        private bool successField;
        
        private string messageField;
        
        private string errorNoField;
        
        private string tokenField;
        
        private string customerNameField;
        
        private AccountType accountTypeField;
        
        private ServiceEndPoint[] serviceEndPointsField;
        
        private SystemDetails systemDetailField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public AccountType AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceEndPoints")]
        public ServiceEndPoint[] ServiceEndPoints {
            get {
                return this.serviceEndPointsField;
            }
            set {
                this.serviceEndPointsField = value;
            }
        }
        
        /// <remarks/>
        public SystemDetails SystemDetail {
            get {
                return this.systemDetailField;
            }
            set {
                this.systemDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public enum AccountType {
        
        /// <remarks/>
        Meta,
        
        /// <remarks/>
        Prop,
        
        /// <remarks/>
        Tradency,
        
        /// <remarks/>
        SPEC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class AuthenticationRequest {
        
        private string tokenField;
        
        private string userIDField;
        
        private string passwordField;
        
        private string brandCodeField;
        
        private string accountNumberField;
        
        private string tradingAccountIDField;
        
        private string fromApplicationField;
        
        private string toApplicationField;
        
        private LoginRequestType requestTypeField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string BrandCode {
            get {
                return this.brandCodeField;
            }
            set {
                this.brandCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TradingAccountID {
            get {
                return this.tradingAccountIDField;
            }
            set {
                this.tradingAccountIDField = value;
            }
        }
        
        /// <remarks/>
        public string FromApplication {
            get {
                return this.fromApplicationField;
            }
            set {
                this.fromApplicationField = value;
            }
        }
        
        /// <remarks/>
        public string ToApplication {
            get {
                return this.toApplicationField;
            }
            set {
                this.toApplicationField = value;
            }
        }
        
        /// <remarks/>
        public LoginRequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public enum LoginRequestType {
        
        /// <remarks/>
        SwitchAccount,
        
        /// <remarks/>
        UserLogin,
        
        /// <remarks/>
        SSOLogin,
        
        /// <remarks/>
        SSOKey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class Activity {
        
        private string typeField;
        
        private string productField;
        
        private string amountField;
        
        private string buySellField;
        
        private string rateField;
        
        private System.DateTime activityDateField;
        
        private string activityIDField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string BuySell {
            get {
                return this.buySellField;
            }
            set {
                this.buySellField = value;
            }
        }
        
        /// <remarks/>
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ActivityDate {
            get {
                return this.activityDateField;
            }
            set {
                this.activityDateField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityID {
            get {
                return this.activityIDField;
            }
            set {
                this.activityIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class BlotterOfActivity {
        
        private Activity[] outputField;
        
        private bool successField;
        
        private string messageField;
        
        private string errorNoField;
        
        /// <remarks/>
        public Activity[] Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class BlotterOfTimeZones {
        
        private TimeZones[] outputField;
        
        private bool successField;
        
        private string messageField;
        
        private string errorNoField;
        
        /// <remarks/>
        public TimeZones[] Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class TimeZones : UserTimeZone {
        
        private long idField;
        
        private string timeZoneIDField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZoneID {
            get {
                return this.timeZoneIDField;
            }
            set {
                this.timeZoneIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeZones))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class UserTimeZone {
        
        private string userTimeZoneIDField;
        
        private string timeZoneNameField;
        
        private string timeZoneStandardNameField;
        
        private bool isSupportDayLightSavingField;
        
        private string dayLightNameField;
        
        private string easternToCustomerTimeZoneOffsetInMinutesField;
        
        private string customerToGMTTimeZoneOffsetInMinutesField;
        
        /// <remarks/>
        public string UserTimeZoneID {
            get {
                return this.userTimeZoneIDField;
            }
            set {
                this.userTimeZoneIDField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZoneName {
            get {
                return this.timeZoneNameField;
            }
            set {
                this.timeZoneNameField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZoneStandardName {
            get {
                return this.timeZoneStandardNameField;
            }
            set {
                this.timeZoneStandardNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSupportDayLightSaving {
            get {
                return this.isSupportDayLightSavingField;
            }
            set {
                this.isSupportDayLightSavingField = value;
            }
        }
        
        /// <remarks/>
        public string DayLightName {
            get {
                return this.dayLightNameField;
            }
            set {
                this.dayLightNameField = value;
            }
        }
        
        /// <remarks/>
        public string EasternToCustomerTimeZoneOffsetInMinutes {
            get {
                return this.easternToCustomerTimeZoneOffsetInMinutesField;
            }
            set {
                this.easternToCustomerTimeZoneOffsetInMinutesField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerToGMTTimeZoneOffsetInMinutes {
            get {
                return this.customerToGMTTimeZoneOffsetInMinutesField;
            }
            set {
                this.customerToGMTTimeZoneOffsetInMinutesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class Order {
        
        private string referenceNumberField;
        
        private string productField;
        
        private string buySellField;
        
        private string contractField;
        
        private string rateField;
        
        private string orderDateField;
        
        private string confirmationNumberField;
        
        private string typeField;
        
        private string basisField;
        
        private string expiryField;
        
        private string statusField;
        
        private string aSSPField;
        
        private string trailingPointsField;
        
        private string dealReferenceField;
        
        /// <remarks/>
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public string BuySell {
            get {
                return this.buySellField;
            }
            set {
                this.buySellField = value;
            }
        }
        
        /// <remarks/>
        public string Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        public string Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmationNumber {
            get {
                return this.confirmationNumberField;
            }
            set {
                this.confirmationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Basis {
            get {
                return this.basisField;
            }
            set {
                this.basisField = value;
            }
        }
        
        /// <remarks/>
        public string Expiry {
            get {
                return this.expiryField;
            }
            set {
                this.expiryField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ASSP {
            get {
                return this.aSSPField;
            }
            set {
                this.aSSPField = value;
            }
        }
        
        /// <remarks/>
        public string TrailingPoints {
            get {
                return this.trailingPointsField;
            }
            set {
                this.trailingPointsField = value;
            }
        }
        
        /// <remarks/>
        public string DealReference {
            get {
                return this.dealReferenceField;
            }
            set {
                this.dealReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class BlotterOfOrder {
        
        private Order[] outputField;
        
        private bool successField;
        
        private string messageField;
        
        private string errorNoField;
        
        /// <remarks/>
        public Order[] Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class Position {
        
        private string productField;
        
        private string contractField;
        
        private string unrealizedField;
        
        private string uSDValueField;
        
        private string currencyValueField;
        
        private string averageRateField;
        
        private string baseCurrencyValueField;
        
        private string limitRateField;
        
        private string stopRateField;
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public string Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        public string Unrealized {
            get {
                return this.unrealizedField;
            }
            set {
                this.unrealizedField = value;
            }
        }
        
        /// <remarks/>
        public string USDValue {
            get {
                return this.uSDValueField;
            }
            set {
                this.uSDValueField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyValue {
            get {
                return this.currencyValueField;
            }
            set {
                this.currencyValueField = value;
            }
        }
        
        /// <remarks/>
        public string AverageRate {
            get {
                return this.averageRateField;
            }
            set {
                this.averageRateField = value;
            }
        }
        
        /// <remarks/>
        public string BaseCurrencyValue {
            get {
                return this.baseCurrencyValueField;
            }
            set {
                this.baseCurrencyValueField = value;
            }
        }
        
        /// <remarks/>
        public string LimitRate {
            get {
                return this.limitRateField;
            }
            set {
                this.limitRateField = value;
            }
        }
        
        /// <remarks/>
        public string StopRate {
            get {
                return this.stopRateField;
            }
            set {
                this.stopRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class BlotterOfPosition {
        
        private Position[] outputField;
        
        private bool successField;
        
        private string messageField;
        
        private string errorNoField;
        
        /// <remarks/>
        public Position[] Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class Margin {
        
        private string postedMarginField;
        
        private string uSDPostedMarginField;
        
        private string realizedProfitField;
        
        private string uSDRealizedProfitField;
        
        private string unrealizedProfitField;
        
        private string marginBalanceField;
        
        private string marginFactorField;
        
        private string availablePositionField;
        
        private string openPositionField;
        
        private string maxDealAvailableField;
        
        /// <remarks/>
        public string PostedMargin {
            get {
                return this.postedMarginField;
            }
            set {
                this.postedMarginField = value;
            }
        }
        
        /// <remarks/>
        public string USDPostedMargin {
            get {
                return this.uSDPostedMarginField;
            }
            set {
                this.uSDPostedMarginField = value;
            }
        }
        
        /// <remarks/>
        public string RealizedProfit {
            get {
                return this.realizedProfitField;
            }
            set {
                this.realizedProfitField = value;
            }
        }
        
        /// <remarks/>
        public string USDRealizedProfit {
            get {
                return this.uSDRealizedProfitField;
            }
            set {
                this.uSDRealizedProfitField = value;
            }
        }
        
        /// <remarks/>
        public string UnrealizedProfit {
            get {
                return this.unrealizedProfitField;
            }
            set {
                this.unrealizedProfitField = value;
            }
        }
        
        /// <remarks/>
        public string MarginBalance {
            get {
                return this.marginBalanceField;
            }
            set {
                this.marginBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string MarginFactor {
            get {
                return this.marginFactorField;
            }
            set {
                this.marginFactorField = value;
            }
        }
        
        /// <remarks/>
        public string AvailablePosition {
            get {
                return this.availablePositionField;
            }
            set {
                this.availablePositionField = value;
            }
        }
        
        /// <remarks/>
        public string OpenPosition {
            get {
                return this.openPositionField;
            }
            set {
                this.openPositionField = value;
            }
        }
        
        /// <remarks/>
        public string MaxDealAvailable {
            get {
                return this.maxDealAvailableField;
            }
            set {
                this.maxDealAvailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class BlotterOfMargin {
        
        private Margin[] outputField;
        
        private bool successField;
        
        private string messageField;
        
        private string errorNoField;
        
        /// <remarks/>
        public Margin[] Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class Service {
        
        private string nameField;
        
        private string urlField;
        
        private string refreshIntervalField;
        
        private string enabledField;
        
        private string visibleField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string RefreshInterval {
            get {
                return this.refreshIntervalField;
            }
            set {
                this.refreshIntervalField = value;
            }
        }
        
        /// <remarks/>
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public string Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class Connection {
        
        private string ipField;
        
        private string portField;
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class ConfigurationSettings {
        
        private byte[] platformImageField;
        
        private string colorStyleField;
        
        private int chartColorSetField;
        
        private Connection[] ratesConnectionField;
        
        private Service[] servicesField;
        
        private bool successField;
        
        private string errorNoField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PlatformImage {
            get {
                return this.platformImageField;
            }
            set {
                this.platformImageField = value;
            }
        }
        
        /// <remarks/>
        public string ColorStyle {
            get {
                return this.colorStyleField;
            }
            set {
                this.colorStyleField = value;
            }
        }
        
        /// <remarks/>
        public int ChartColorSet {
            get {
                return this.chartColorSetField;
            }
            set {
                this.chartColorSetField = value;
            }
        }
        
        /// <remarks/>
        public Connection[] RatesConnection {
            get {
                return this.ratesConnectionField;
            }
            set {
                this.ratesConnectionField = value;
            }
        }
        
        /// <remarks/>
        public Service[] Services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class ProductSetting {
        
        private string productField;
        
        private string marginFactorField;
        
        private string notationField;
        
        private string counterProductField;
        
        private string contractProductField;
        
        private string tradeSizeField;
        
        private string orderSizeField;
        
        private string defaultTradeLotsField;
        
        private string defaultOrderLotsField;
        
        private string maxTradeLotsField;
        
        private string maxOrderLotsField;
        
        private string cancelOrderPipsField;
        
        private string maxOrderPipsField;
        
        private string pipDifferenceField;
        
        private bool activeField;
        
        private string orderField;
        
        private bool subscribedField;
        
        private bool quickPairField;
        
        private string maxPositionField;
        
        private string decimalPlacesField;
        
        private string aliasNameField;
        
        private string descriptionField;
        
        private string boldIndexField;
        
        private string superScriptIndexField;
        
        private string contractExpiryDescriptionField;
        
        private string dailyClosureExpiryTimeDescriptionField;
        
        private string unitsPerLotDescriptionField;
        
        private string minimumTickDescriptionField;
        
        private string orderPipsAwayField;
        
        private udProductType typeField;
        
        private udProductType productGroupField;
        
        private string minimumToleranceField;
        
        private string toleranceField;
        
        private bool isOnWatchListField;
        
        private bool isPopularMarketField;
        
        private string popularMarketOrderField;
        
        private string watchlistSortOrderField;
        
        private string dealBoxSortOrderField;
        
        private string minimumTickValueField;
        
        private string underlyingExchangeField;
        
        private string contactValueDescriptionField;
        
        private string tickValueField;
        
        private string productDisplayTreeField;
        
        private string tradingHoursField;
        
        private string expirationDateField;
        
        private string underlyingExchangeMonthField;
        
        private string expirationDateTimeField;
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public string MarginFactor {
            get {
                return this.marginFactorField;
            }
            set {
                this.marginFactorField = value;
            }
        }
        
        /// <remarks/>
        public string Notation {
            get {
                return this.notationField;
            }
            set {
                this.notationField = value;
            }
        }
        
        /// <remarks/>
        public string CounterProduct {
            get {
                return this.counterProductField;
            }
            set {
                this.counterProductField = value;
            }
        }
        
        /// <remarks/>
        public string ContractProduct {
            get {
                return this.contractProductField;
            }
            set {
                this.contractProductField = value;
            }
        }
        
        /// <remarks/>
        public string TradeSize {
            get {
                return this.tradeSizeField;
            }
            set {
                this.tradeSizeField = value;
            }
        }
        
        /// <remarks/>
        public string OrderSize {
            get {
                return this.orderSizeField;
            }
            set {
                this.orderSizeField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultTradeLots {
            get {
                return this.defaultTradeLotsField;
            }
            set {
                this.defaultTradeLotsField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultOrderLots {
            get {
                return this.defaultOrderLotsField;
            }
            set {
                this.defaultOrderLotsField = value;
            }
        }
        
        /// <remarks/>
        public string MaxTradeLots {
            get {
                return this.maxTradeLotsField;
            }
            set {
                this.maxTradeLotsField = value;
            }
        }
        
        /// <remarks/>
        public string MaxOrderLots {
            get {
                return this.maxOrderLotsField;
            }
            set {
                this.maxOrderLotsField = value;
            }
        }
        
        /// <remarks/>
        public string CancelOrderPips {
            get {
                return this.cancelOrderPipsField;
            }
            set {
                this.cancelOrderPipsField = value;
            }
        }
        
        /// <remarks/>
        public string MaxOrderPips {
            get {
                return this.maxOrderPipsField;
            }
            set {
                this.maxOrderPipsField = value;
            }
        }
        
        /// <remarks/>
        public string PipDifference {
            get {
                return this.pipDifferenceField;
            }
            set {
                this.pipDifferenceField = value;
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public bool Subscribed {
            get {
                return this.subscribedField;
            }
            set {
                this.subscribedField = value;
            }
        }
        
        /// <remarks/>
        public bool QuickPair {
            get {
                return this.quickPairField;
            }
            set {
                this.quickPairField = value;
            }
        }
        
        /// <remarks/>
        public string MaxPosition {
            get {
                return this.maxPositionField;
            }
            set {
                this.maxPositionField = value;
            }
        }
        
        /// <remarks/>
        public string DecimalPlaces {
            get {
                return this.decimalPlacesField;
            }
            set {
                this.decimalPlacesField = value;
            }
        }
        
        /// <remarks/>
        public string AliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string BoldIndex {
            get {
                return this.boldIndexField;
            }
            set {
                this.boldIndexField = value;
            }
        }
        
        /// <remarks/>
        public string SuperScriptIndex {
            get {
                return this.superScriptIndexField;
            }
            set {
                this.superScriptIndexField = value;
            }
        }
        
        /// <remarks/>
        public string ContractExpiryDescription {
            get {
                return this.contractExpiryDescriptionField;
            }
            set {
                this.contractExpiryDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DailyClosureExpiryTimeDescription {
            get {
                return this.dailyClosureExpiryTimeDescriptionField;
            }
            set {
                this.dailyClosureExpiryTimeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string UnitsPerLotDescription {
            get {
                return this.unitsPerLotDescriptionField;
            }
            set {
                this.unitsPerLotDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string MinimumTickDescription {
            get {
                return this.minimumTickDescriptionField;
            }
            set {
                this.minimumTickDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OrderPipsAway {
            get {
                return this.orderPipsAwayField;
            }
            set {
                this.orderPipsAwayField = value;
            }
        }
        
        /// <remarks/>
        public udProductType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public udProductType ProductGroup {
            get {
                return this.productGroupField;
            }
            set {
                this.productGroupField = value;
            }
        }
        
        /// <remarks/>
        public string MinimumTolerance {
            get {
                return this.minimumToleranceField;
            }
            set {
                this.minimumToleranceField = value;
            }
        }
        
        /// <remarks/>
        public string Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOnWatchList {
            get {
                return this.isOnWatchListField;
            }
            set {
                this.isOnWatchListField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPopularMarket {
            get {
                return this.isPopularMarketField;
            }
            set {
                this.isPopularMarketField = value;
            }
        }
        
        /// <remarks/>
        public string PopularMarketOrder {
            get {
                return this.popularMarketOrderField;
            }
            set {
                this.popularMarketOrderField = value;
            }
        }
        
        /// <remarks/>
        public string WatchlistSortOrder {
            get {
                return this.watchlistSortOrderField;
            }
            set {
                this.watchlistSortOrderField = value;
            }
        }
        
        /// <remarks/>
        public string DealBoxSortOrder {
            get {
                return this.dealBoxSortOrderField;
            }
            set {
                this.dealBoxSortOrderField = value;
            }
        }
        
        /// <remarks/>
        public string MinimumTickValue {
            get {
                return this.minimumTickValueField;
            }
            set {
                this.minimumTickValueField = value;
            }
        }
        
        /// <remarks/>
        public string UnderlyingExchange {
            get {
                return this.underlyingExchangeField;
            }
            set {
                this.underlyingExchangeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactValueDescription {
            get {
                return this.contactValueDescriptionField;
            }
            set {
                this.contactValueDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string TickValue {
            get {
                return this.tickValueField;
            }
            set {
                this.tickValueField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDisplayTree {
            get {
                return this.productDisplayTreeField;
            }
            set {
                this.productDisplayTreeField = value;
            }
        }
        
        /// <remarks/>
        public string TradingHours {
            get {
                return this.tradingHoursField;
            }
            set {
                this.tradingHoursField = value;
            }
        }
        
        /// <remarks/>
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string UnderlyingExchangeMonth {
            get {
                return this.underlyingExchangeMonthField;
            }
            set {
                this.underlyingExchangeMonthField = value;
            }
        }
        
        /// <remarks/>
        public string ExpirationDateTime {
            get {
                return this.expirationDateTimeField;
            }
            set {
                this.expirationDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public enum udProductType {
        
        /// <remarks/>
        CURRENCY,
        
        /// <remarks/>
        CFD,
        
        /// <remarks/>
        METALS,
        
        /// <remarks/>
        OIL,
        
        /// <remarks/>
        OTHERS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class AccountSettings {
        
        private string basePairField;
        
        private string featuresField;
        
        private string blowoutLevelField;
        
        private bool isNFARegulatedField;
        
        private bool isDealAtMarketField;
        
        private bool isAgencyField;
        
        /// <remarks/>
        public string BasePair {
            get {
                return this.basePairField;
            }
            set {
                this.basePairField = value;
            }
        }
        
        /// <remarks/>
        public string Features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
            }
        }
        
        /// <remarks/>
        public string BlowoutLevel {
            get {
                return this.blowoutLevelField;
            }
            set {
                this.blowoutLevelField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNFARegulated {
            get {
                return this.isNFARegulatedField;
            }
            set {
                this.isNFARegulatedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDealAtMarket {
            get {
                return this.isDealAtMarketField;
            }
            set {
                this.isDealAtMarketField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAgency {
            get {
                return this.isAgencyField;
            }
            set {
                this.isAgencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class Settings {
        
        private AccountSettings accountSettingsField;
        
        private ProductSetting[] productSettingsField;
        
        private UserTimeZone userTimeZonesField;
        
        private bool successField;
        
        private string messageField;
        
        private string errorNoField;
        
        /// <remarks/>
        public AccountSettings AccountSettings {
            get {
                return this.accountSettingsField;
            }
            set {
                this.accountSettingsField = value;
            }
        }
        
        /// <remarks/>
        public ProductSetting[] ProductSettings {
            get {
                return this.productSettingsField;
            }
            set {
                this.productSettingsField = value;
            }
        }
        
        /// <remarks/>
        public UserTimeZone UserTimeZones {
            get {
                return this.userTimeZonesField;
            }
            set {
                this.userTimeZonesField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationResult2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class AuthenticationResult {
        
        private bool successField;
        
        private string errorNoField;
        
        private string tokenField;
        
        private string customerNameField;
        
        private string configurationServiceField;
        
        private string tradingServiceField;
        
        private string chartingServiceField;
        
        private string researchServiceField;
        
        private string profileServiceField;
        
        private string reportServiceField;
        
        private bool isMETAField;
        
        private string metaServerNameField;
        
        private string metaAccountNumberField;
        
        private string mETAServiceField;
        
        private string alertServiceField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string configurationService {
            get {
                return this.configurationServiceField;
            }
            set {
                this.configurationServiceField = value;
            }
        }
        
        /// <remarks/>
        public string tradingService {
            get {
                return this.tradingServiceField;
            }
            set {
                this.tradingServiceField = value;
            }
        }
        
        /// <remarks/>
        public string chartingService {
            get {
                return this.chartingServiceField;
            }
            set {
                this.chartingServiceField = value;
            }
        }
        
        /// <remarks/>
        public string researchService {
            get {
                return this.researchServiceField;
            }
            set {
                this.researchServiceField = value;
            }
        }
        
        /// <remarks/>
        public string profileService {
            get {
                return this.profileServiceField;
            }
            set {
                this.profileServiceField = value;
            }
        }
        
        /// <remarks/>
        public string reportService {
            get {
                return this.reportServiceField;
            }
            set {
                this.reportServiceField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMETA {
            get {
                return this.isMETAField;
            }
            set {
                this.isMETAField = value;
            }
        }
        
        /// <remarks/>
        public string MetaServerName {
            get {
                return this.metaServerNameField;
            }
            set {
                this.metaServerNameField = value;
            }
        }
        
        /// <remarks/>
        public string MetaAccountNumber {
            get {
                return this.metaAccountNumberField;
            }
            set {
                this.metaAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string METAService {
            get {
                return this.mETAServiceField;
            }
            set {
                this.mETAServiceField = value;
            }
        }
        
        /// <remarks/>
        public string AlertService {
            get {
                return this.alertServiceField;
            }
            set {
                this.alertServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.GainCapital.com.WebServices")]
    public partial class AuthenticationResult2 : AuthenticationResult {
        
        private Settings settingsField;
        
        private ConfigurationSettings configurationSettingsField;
        
        private BlotterOfMargin marginBlotterField;
        
        private BlotterOfPosition positionBlotterField;
        
        private BlotterOfOrder orderBlotterField;
        
        private BlotterOfTimeZones timeZoneBlotterField;
        
        private BlotterOfActivity activityBlotterField;
        
        /// <remarks/>
        public Settings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        public ConfigurationSettings ConfigurationSettings {
            get {
                return this.configurationSettingsField;
            }
            set {
                this.configurationSettingsField = value;
            }
        }
        
        /// <remarks/>
        public BlotterOfMargin MarginBlotter {
            get {
                return this.marginBlotterField;
            }
            set {
                this.marginBlotterField = value;
            }
        }
        
        /// <remarks/>
        public BlotterOfPosition PositionBlotter {
            get {
                return this.positionBlotterField;
            }
            set {
                this.positionBlotterField = value;
            }
        }
        
        /// <remarks/>
        public BlotterOfOrder OrderBlotter {
            get {
                return this.orderBlotterField;
            }
            set {
                this.orderBlotterField = value;
            }
        }
        
        /// <remarks/>
        public BlotterOfTimeZones TimeZoneBlotter {
            get {
                return this.timeZoneBlotterField;
            }
            set {
                this.timeZoneBlotterField = value;
            }
        }
        
        /// <remarks/>
        public BlotterOfActivity ActivityBlotter {
            get {
                return this.activityBlotterField;
            }
            set {
                this.activityBlotterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AuthenticateCredentialsCompletedEventHandler(object sender, AuthenticateCredentialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AuthenticateCredentialsWithBrandCodeCompletedEventHandler(object sender, AuthenticateCredentialsWithBrandCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCredentialsWithBrandCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCredentialsWithBrandCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AuthenticateLinkedAccountCompletedEventHandler(object sender, AuthenticateLinkedAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateLinkedAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateLinkedAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetServerTimeCompletedEventHandler(object sender, GetServerTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SingleSignOnCompletedEventHandler(object sender, SingleSignOnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SingleSignOnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SingleSignOnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AuthenticateWithDetailsCompletedEventHandler(object sender, AuthenticateWithDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateWithDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateWithDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult2)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591