//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmodatForex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.efxnow.com/DEMOWebServices2.8/Service.asmx")]
        public string AsmodatForex_com_efxnow_api_Gain_x0020_Capital_x0020___x0020_AutoEx_x0020_Trading_x0020_API {
            get {
                return ((string)(this["AsmodatForex_com_efxnow_api_Gain_x0020_Capital_x0020___x0020_AutoEx_x0020_Trading" +
                    "_x0020_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://democharting.efxnow.com/Charting/ChartingService.asmx")]
        public string AsmodatForex_com_efxnow_democharting_chartingservice_ChartingService {
            get {
                return ((string)(this["AsmodatForex_com_efxnow_democharting_chartingservice_ChartingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demoweb.efxnow.com/gaincapitalwebservices/authenticate/authenticationservi" +
            "ce.asmx")]
        public string AsmodatForex_com_efxnow_demoweb_authentyficationservice_AuthenticationService {
            get {
                return ((string)(this["AsmodatForex_com_efxnow_demoweb_authentyficationservice_AuthenticationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demoweb.efxnow.com/gaincapitalwebservices/rates/ratesservice.asmx")]
        public string AsmodatForex_com_efxnow_demoweb_ratesservice_RatesService {
            get {
                return ((string)(this["AsmodatForex_com_efxnow_demoweb_ratesservice_RatesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demoweb.efxnow.com/gaincapitalwebservices/trading/tradingservice.asmx")]
        public string AsmodatForex_com_efxnow_demoweb_tradingservice_TradingService {
            get {
                return ((string)(this["AsmodatForex_com_efxnow_demoweb_tradingservice_TradingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demoweb.efxnow.com/GainCapitalWebServices/Configuration/ConfigurationServi" +
            "ce.asmx")]
        public string AsmodatForex_com_efxnow_demoweb_configurationservice_ConfigurationService {
            get {
                return ((string)(this["AsmodatForex_com_efxnow_demoweb_configurationservice_ConfigurationService"]));
            }
        }
    }
}
